version: "3"
services:
 app:
  build: .
  volumes:
   - .:/ecomm_api
  ports:
   - 8000:8000
  image: app:ecomm_api
  container_name: ecomm_api_container
  command: python manage.py runserver 0.0.0.0:8000
  